### ISSUE TITLE
rxvt-unicode: --enable-unicode3

### ISSUE THREAD

**Issue by salcedo** [Homebrew/homebrew-x11#167]
Added --enable-unicode3 to list of configure options. This was needed for things like vim airline to look right. Please consider adding this option by default?

**Comment by apjanke** [comment]
This probably makes sense, and is certainly something we could at least expose as an option at the formula level.

There's a performance cost. From [rxvt-unicode's README.configure](https://github.com/exg/rxvt-unicode/blob/431820eaf01da39824073c85b0d9bf89542c0af8/README.configure#L51-L63):

```
    --enable-unicode3 (default: off)
        Recommended to stay off unless you really need non-BMP characters.

        Enable direct support for displaying unicode codepoints above 65535
        (the basic multilingual page). This increases storage requirements
        per character from 2 to 4 bytes. X11 fonts do not yet support these
        extra characters, but Xft does.

        Please note that rxvt-unicode can store unicode code points >65535
        even without this flag, but the number of such characters is limited
        to a few thousand (shared with combining characters, see next
        switch), and right now rxvt-unicode cannot display them
        (input/output and cut&paste still work, though).
```

Homebrew tends to prefer enabling features by default instead of optimizing for performance, so this would probably make sense to enable by default in the Homebrew build, even though it's off by default in the rxvt-unicode distribution. Users who want to optimize for performance could build `--without-unicode3`. Thoughts from other folks on which should be the default here?

And salcedo, is there a quick way to test the extended character functionality you need here without having to set up vim airline?

**Comment by apjanke** [comment]
Seems like pretty low overhead for `--enable-unicode3`, just a few hundred KB of resident memory with a default scrollback size.

I built `urxvt` 6.22 on 10.9.5 with and without `--enable-unicode3`, ran both, and filled up their scrollback buffers with `git log | cat`. Not much difference.

<img width="582" alt="screen shot 2016-02-23 at 6 14 21 pm" src="https://cloud.githubusercontent.com/assets/2618447/13270064/967c1e04-da59-11e5-9c99-a3b2277cb092.png">

<img width="743" alt="screen shot 2016-02-23 at 6 18 57 pm" src="https://cloud.githubusercontent.com/assets/2618447/13270123/f098c6d0-da59-11e5-9739-32619626f31b.png">

I think that makes enabling `unicode3` by default reasonable. And that way users who wanted to use non-BMP characters would get it out of the box, and wouldn't have to know to go looking for this option.

**Comment by apjanke** [comment]
We've added a `--with-unicode3` option to the `rxvt-unicode` formula and made it the default. (#187)
